# frozen_string_literal: true

# Generated by tsykvas_rails_template:install. Canonical example of the
# `endpoint` DSL: controllers stay one-liners, business logic lives in the
# operation, presentation in the component, authorization in the policy.
class HomeController < ApplicationController
  def index
    endpoint Home::Operation::Index, Home::Component::Index
  end
end
